sonar.projectKey=paila-rakesh004_Smart-Loan-App
sonar.organization=paila-rakesh004

sonar.sources=backend/users,backend/loans,frontend
sonar.tests=backend
sonar.test.inclusions=backend/**/tests.py
sonar.exclusions=backend/**/tests.py,backend/**/migrations/**,backend/**/venv/**,backend/manage.py,frontend/.next/**
sonar.coverage.exclusions=frontend/**,backend/**/migrations/**,backend/loans/utility/**,backend/loans/ml_model/**
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.sourceEncoding=UTF-8
