# Generated by Django 6.0.2 on 2026-02-25 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('risk_score', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(max_length=100)),
                ('organization_name', models.CharField(max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_type', models.CharField(max_length=50)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tenure', models.IntegerField(help_text='In Months')),
                ('no_of_dependents', models.IntegerField(default=0)),
                ('cibil_score', models.IntegerField(default=0)),
                ('residential_assets_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('commercial_assets_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('luxury_assets_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('bank_asset_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('id_proof', models.FileField(upload_to='documents/id_proofs/')),
                ('address_proof', models.FileField(upload_to='documents/address_proofs/')),
                ('salary_slips', models.FileField(upload_to='documents/salary_slips/')),
                ('emp_id_card', models.FileField(upload_to='documents/emp_ids/')),
                ('nominee_id_card', models.FileField(upload_to='documents/nominee_ids/')),
                ('nominee_address_proof', models.FileField(upload_to='documents/nominee_address/')),
                ('nominee_sign', models.FileField(upload_to='documents/nominee_signs/')),
                ('nominee_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
