# Generated by Django 6.0.2 on 2026-02-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='bank_asset_value',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='commercial_assets_value',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='luxury_assets_value',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='no_of_dependents',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='residential_assets_value',
        ),
    ]
