# Generated by Django 6.0.2 on 2026-02-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='officer_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
