# Generated by Django 6.0.2 on 2026-03-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_cibil_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='address_proof',
            field=models.FileField(upload_to='address_proofs/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='emp_id_card',
            field=models.FileField(upload_to='emp_ids/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='id_proof',
            field=models.FileField(upload_to='id_proofs/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='nominee_address_proof',
            field=models.FileField(upload_to='nominee_address/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='nominee_id_card',
            field=models.FileField(upload_to='nominee_ids/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='nominee_sign',
            field=models.FileField(upload_to='nominee_signs/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='salary_slips',
            field=models.FileField(upload_to='salary_slips/'),
        ),
    ]
