# Generated by Django 6.0.3 on 2026-03-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
        ('loans', '0003_alter_loanapplication_address_proof_and_more'),
    ]

    operations = [
    ]
