# Generated by Django 6.0.3 on 2026-03-09 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_merge_20260309_1432'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='tenure',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ExternalFinancialHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_at_previous_bank', models.PositiveIntegerField(default=0)),
                ('annual_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_transaction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fixed_deposits_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_loans_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('proof_of_oldbank', models.FileField(blank=True, null=True, upload_to='proofs/vintage/')),
                ('income_proof', models.FileField(blank=True, null=True, upload_to='proofs/income/')),
                ('bank_statements', models.FileField(blank=True, null=True, upload_to='proofs/statements/')),
                ('fd_receipts', models.FileField(blank=True, null=True, upload_to='proofs/fds/')),
                ('pending_loan_docs', models.FileField(blank=True, null=True, upload_to='proofs/loans/')),
                ('calculated_cibil_score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
