# Generated by Django 6.0.3 on 2026-03-20 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_remove_loanapplication_bank_asset_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='bank_asset_value',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='commercial_assets_value',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='luxury_assets_value',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='no_of_dependents',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='residential_assets_value',
        ),
    ]
