# Generated by Django 6.0.3 on 2026-03-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_remove_loanapplication_bank_asset_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='ai_verification_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
