# Generated by Django 6.0.3 on 2026-03-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loanapplication_ai_verification_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='address_proof',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='id_proof',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='bank_statements',
            field=models.FileField(blank=True, null=True, upload_to='temporary_proofs/bank_statements/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='itr_document',
            field=models.FileField(blank=True, null=True, upload_to='temporary_proofs/itr_docs/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='emp_id_card',
            field=models.FileField(blank=True, null=True, upload_to='emp_ids/'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='salary_slips',
            field=models.FileField(blank=True, null=True, upload_to='temporary_proofs/salary_slips/'),
        ),
        migrations.DeleteModel(
            name='ExternalFinancialHistory',
        ),
    ]
