# Generated by Django 6.0.3 on 2026-04-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0008_remove_loanapplication_address_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='nominee_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='nominee_ration_card',
            field=models.FileField(blank=True, null=True, upload_to='nominee_rationcards/'),
        ),
    ]
