# Generated by Django 6.0.3 on 2026-04-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_loanapplication_nominee_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='occ',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='cibil_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='risk_score',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
