# Generated by Django 6.0.3 on 2026-04-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_loanapplication_occ_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='nominee_address_proof',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='nominee_age',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='nominee_id_card',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='nominee_ration_card',
        ),
        migrations.RemoveField(
            model_name='loanapplication',
            name='nominee_sign',
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='doc_10th_cert',
            field=models.FileField(blank=True, null=True, upload_to='documents/education/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='doc_12th_cert',
            field=models.FileField(blank=True, null=True, upload_to='documents/education/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='doc_admission_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/education/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='doc_agreement_sale',
            field=models.FileField(blank=True, null=True, upload_to='documents/home/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='doc_building_plan',
            field=models.FileField(blank=True, null=True, upload_to='documents/home/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='doc_degree_cert',
            field=models.FileField(blank=True, null=True, upload_to='documents/education/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='doc_encumbrance_cert',
            field=models.FileField(blank=True, null=True, upload_to='documents/home/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='doc_fee_structure',
            field=models.FileField(blank=True, null=True, upload_to='documents/education/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='doc_guarantor_financials',
            field=models.FileField(blank=True, null=True, upload_to='documents/education/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='doc_guarantor_kyc',
            field=models.FileField(blank=True, null=True, upload_to='documents/education/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='doc_noc',
            field=models.FileField(blank=True, null=True, upload_to='documents/home/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='guarantor_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='guarantor_organization',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='nominee_relation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
