# Generated by Django 6.0.3 on 2026-04-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_remove_loanapplication_nominee_address_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='nominee_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
