# Generated by Django 6.0.3 on 2026-04-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0012_loanapplication_nominee_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='doc_guarantor_photo',
            field=models.FileField(blank=True, null=True, upload_to='documents/education/'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='doc_guarantor_signature',
            field=models.FileField(blank=True, null=True, upload_to='documents/education/'),
        ),
    ]
