# Generated by Django 6.0.4 on 2026-04-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0013_loanapplication_doc_guarantor_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='guarantor_organization',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='nominee_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='nominee_relation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='occ',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='officer_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='risk_score',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
