# Generated by Django 6.0.4 on 2026-04-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_alter_loanapplication_guarantor_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Eligible', 'Eligible'), ('Not Eligible', 'Not Eligible')], default='Pending', max_length=20),
        ),
    ]
