# Generated by Django 6.0.3 on 2026-03-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_otp_expiry_user_reset_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_card_file',
            field=models.FileField(blank=True, null=True, upload_to='vault/aadhar_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='pan_card_file',
            field=models.FileField(blank=True, null=True, upload_to='vault/pan_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='vault/photos/'),
        ),
    ]
