# Generated by Django 6.0.4 on 2026-04-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_aadhar_number_alter_user_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFinancialData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('years_as_customer', models.IntegerField()),
                ('total_transaction_amount', models.FloatField()),
                ('total_loan_amount', models.FloatField()),
                ('tenure_months', models.IntegerField()),
                ('income', models.FloatField()),
                ('pending_loan', models.FloatField()),
                ('fixed_deposits', models.FloatField()),
                ('credit_score', models.IntegerField()),
            ],
            options={
                'db_table': 'user_financial_data',
            },
        ),
    ]
