# Generated by Django 6.0.4 on 2026-04-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userfinancialdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfinancialdata',
            options={},
        ),
    ]
